version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: justifyMeAdmin
      POSTGRES_PASSWORD: justifyMePassword
      POSTGRES_DB: justifyMeDb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./init:/docker-entrypoint-initdb.d
    networks:
       - app
    container_name: postgres
    restart: always

networks:
  app:
    driver: bridge

volumes:
  postgres: